RUN set -eu -o pipefail
RUN update-alternatives --set php /usr/bin/php${DDEV_PHP_VERSION}
RUN [ -f /usr/local/bin/pie ] || (curl -L https://github.com/php/pie/releases/latest/download/pie.phar -o /usr/local/bin/pie && chmod +x /usr/local/bin/pie)
RUN apt-get update -y
RUN DEBIAN_FRONTEND=noninteractive \
	apt-get install \
	-y \
	php${DDEV_PHP_VERSION}-dev \
	zlib1g-dev
RUN pie install --force noisebynorthwest/php-spx
